name: Docker Image CI

on:
  push: # push 时触发ci
    branches: [master] # 作用于master分支

jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest

    steps:
      # 拉取master分支代码
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到阿里云容器镜像服务
      - name: build and push docker image
        run: |
          docker version
          docker login --username=wjourney --password=wenwen0815
          
          docker image build -t nextjs-demo:latest .
          docker tag nextjs-demo:latest wjourney/nextjs-demo:latest 
          docker push wjourney/nextjs-demo
      # 登录远程服务器，拉取镜像，制作并重启容器
      # https://github.com/marketplace/actions/remote-ssh-commands
      - name: remote deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull wjourneynextjs-demo:latest
            docker run -p 3005:3005 wjourney/nextjs-demo:latest