name: Docker Image CI

on:
  push: # push 时触发ci
    branches: [master] # 作用于master分支

jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest

    steps:
      # 拉取master分支代码
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到阿里云容器镜像服务
      - name: build and push docker image
        run: |
          docker version
          docker login --username=wjourney --password=wenwen0815
          
          docker image build -t nextjs-demo:latest .
          docker tag nextjs-demo registry.cn-hangzhou.aliyuncs.com/test-blog/nextjs-demo:latest
          docker push registry.cn-hangzhou.aliyuncs.com/test-blog/nextjs-demo:latest
          docker logout
      # 登录远程服务器，拉取镜像，制作并重启容器
      # https://github.com/marketplace/actions/remote-ssh-commands
      - name: ssh remote deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /
            echo -e "1.docker login start==>"
            docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

            echo -e "2.docker stop nextjs-demo container==>"
            docker container stop nextjs-demo

            echo -e "3.docker conatainer rm==>"
            docker container rm nextjs-demo

            echo -e "4.docker image rm==>"
            docker image rm registry.cn-hangzhou.aliyuncs.com/test-blog/nextjs-demo:latest

            echo -e "5.docker pull==>"
            docker pull registry.cn-hangzhou.aliyuncs.com/test-blog/nextjs-demo:latest

            echo -e "6.docker container create and start==>"
            docker container run -d -p 80:3000 --name nextjs-demo registry.cn-hangzhou.aliyuncs.com/test-blog/nextjs-demo:latest

            echo -e "7.docker logout==>"
            docker logout
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
